// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/testing/messages.proto

package testing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The type of payload that should be returned.
type PayloadType int32

const (
	// Compressable text format.
	PayloadType_COMPRESSABLE PayloadType = 0
)

var PayloadType_name = map[int32]string{
	0: "COMPRESSABLE",
}

var PayloadType_value = map[string]int32{
	"COMPRESSABLE": 0,
}

func (x PayloadType) String() string {
	return proto.EnumName(PayloadType_name, int32(x))
}

func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{0}
}

// The type of route that a client took to reach a server w.r.t. gRPCLB.
// The server must fill in "fallback" if it detects that the RPC reached
// the server via the "gRPCLB fallback" path, and "backend" if it detects
// that the RPC reached the server via "gRPCLB backend" path (i.e. if it got
// the address of this server from the gRPCLB server BalanceLoad RPC). Exactly
// how this detection is done is context and server dependant.
type GrpclbRouteType int32

const (
	// Server didn't detect the route that a client took to reach it.
	GrpclbRouteType_GRPCLB_ROUTE_TYPE_UNKNOWN GrpclbRouteType = 0
	// Indicates that a client reached a server via gRPCLB fallback.
	GrpclbRouteType_GRPCLB_ROUTE_TYPE_FALLBACK GrpclbRouteType = 1
	// Indicates that a client reached a server as a gRPCLB-given backend.
	GrpclbRouteType_GRPCLB_ROUTE_TYPE_BACKEND GrpclbRouteType = 2
)

var GrpclbRouteType_name = map[int32]string{
	0: "GRPCLB_ROUTE_TYPE_UNKNOWN",
	1: "GRPCLB_ROUTE_TYPE_FALLBACK",
	2: "GRPCLB_ROUTE_TYPE_BACKEND",
}

var GrpclbRouteType_value = map[string]int32{
	"GRPCLB_ROUTE_TYPE_UNKNOWN":  0,
	"GRPCLB_ROUTE_TYPE_FALLBACK": 1,
	"GRPCLB_ROUTE_TYPE_BACKEND":  2,
}

func (x GrpclbRouteType) String() string {
	return proto.EnumName(GrpclbRouteType_name, int32(x))
}

func (GrpclbRouteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{1}
}

// TODO(dgq): Go back to using well-known types once
// https://github.com/grpc/grpc/issues/6980 has been fixed.
// import "google/protobuf/wrappers.proto";
type BoolValue struct {
	// The bool value.
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{0}
}

func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

// A block of data, to simply increase gRPC message size.
type Payload struct {
	// The type of data in body.
	Type PayloadType `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.testing.PayloadType" json:"type,omitempty"`
	// Primary contents of payload.
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetType() PayloadType {
	if m != nil {
		return m.Type
	}
	return PayloadType_COMPRESSABLE
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// A protobuf representation for grpc status. This is used by test
// clients to specify a status that the server should attempt to return.
type EchoStatus struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoStatus) Reset()         { *m = EchoStatus{} }
func (m *EchoStatus) String() string { return proto.CompactTextString(m) }
func (*EchoStatus) ProtoMessage()    {}
func (*EchoStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{2}
}

func (m *EchoStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoStatus.Unmarshal(m, b)
}
func (m *EchoStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoStatus.Marshal(b, m, deterministic)
}
func (m *EchoStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoStatus.Merge(m, src)
}
func (m *EchoStatus) XXX_Size() int {
	return xxx_messageInfo_EchoStatus.Size(m)
}
func (m *EchoStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EchoStatus proto.InternalMessageInfo

func (m *EchoStatus) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EchoStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Unary request.
type SimpleRequest struct {
	// Desired payload type in the response from the server.
	// If response_type is RANDOM, server randomly chooses one from other formats.
	ResponseType PayloadType `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=grpc.testing.PayloadType" json:"response_type,omitempty"`
	// Desired payload size in the response from the server.
	ResponseSize int32 `protobuf:"varint,2,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	// Optional input payload sent along with the request.
	Payload *Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Whether SimpleResponse should include username.
	FillUsername bool `protobuf:"varint,4,opt,name=fill_username,json=fillUsername,proto3" json:"fill_username,omitempty"`
	// Whether SimpleResponse should include OAuth scope.
	FillOauthScope bool `protobuf:"varint,5,opt,name=fill_oauth_scope,json=fillOauthScope,proto3" json:"fill_oauth_scope,omitempty"`
	// Whether to request the server to compress the response. This field is
	// "nullable" in order to interoperate seamlessly with clients not able to
	// implement the full compression tests by introspecting the call to verify
	// the response's compression status.
	ResponseCompressed *BoolValue `protobuf:"bytes,6,opt,name=response_compressed,json=responseCompressed,proto3" json:"response_compressed,omitempty"`
	// Whether server should return a given status
	ResponseStatus *EchoStatus `protobuf:"bytes,7,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	// Whether the server should expect this request to be compressed.
	ExpectCompressed *BoolValue `protobuf:"bytes,8,opt,name=expect_compressed,json=expectCompressed,proto3" json:"expect_compressed,omitempty"`
	// Whether SimpleResponse should include server_id.
	FillServerId bool `protobuf:"varint,9,opt,name=fill_server_id,json=fillServerId,proto3" json:"fill_server_id,omitempty"`
	// Whether SimpleResponse should include grpclb_route_type.
	FillGrpclbRouteType  bool     `protobuf:"varint,10,opt,name=fill_grpclb_route_type,json=fillGrpclbRouteType,proto3" json:"fill_grpclb_route_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{3}
}

func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (m *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(m, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetResponseType() PayloadType {
	if m != nil {
		return m.ResponseType
	}
	return PayloadType_COMPRESSABLE
}

func (m *SimpleRequest) GetResponseSize() int32 {
	if m != nil {
		return m.ResponseSize
	}
	return 0
}

func (m *SimpleRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SimpleRequest) GetFillUsername() bool {
	if m != nil {
		return m.FillUsername
	}
	return false
}

func (m *SimpleRequest) GetFillOauthScope() bool {
	if m != nil {
		return m.FillOauthScope
	}
	return false
}

func (m *SimpleRequest) GetResponseCompressed() *BoolValue {
	if m != nil {
		return m.ResponseCompressed
	}
	return nil
}

func (m *SimpleRequest) GetResponseStatus() *EchoStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *SimpleRequest) GetExpectCompressed() *BoolValue {
	if m != nil {
		return m.ExpectCompressed
	}
	return nil
}

func (m *SimpleRequest) GetFillServerId() bool {
	if m != nil {
		return m.FillServerId
	}
	return false
}

func (m *SimpleRequest) GetFillGrpclbRouteType() bool {
	if m != nil {
		return m.FillGrpclbRouteType
	}
	return false
}

// Unary response, as configured by the request.
type SimpleResponse struct {
	// Payload to increase message size.
	Payload *Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The user the request came from, for verifying authentication was
	// successful when the client expected it.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// OAuth scope.
	OauthScope string `protobuf:"bytes,3,opt,name=oauth_scope,json=oauthScope,proto3" json:"oauth_scope,omitempty"`
	// Server ID. This must be unique among different server instances,
	// but the same across all RPC's made to a particular server instance.
	ServerId string `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// gRPCLB Path.
	GrpclbRouteType      GrpclbRouteType `protobuf:"varint,5,opt,name=grpclb_route_type,json=grpclbRouteType,proto3,enum=grpc.testing.GrpclbRouteType" json:"grpclb_route_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{4}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SimpleResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SimpleResponse) GetOauthScope() string {
	if m != nil {
		return m.OauthScope
	}
	return ""
}

func (m *SimpleResponse) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *SimpleResponse) GetGrpclbRouteType() GrpclbRouteType {
	if m != nil {
		return m.GrpclbRouteType
	}
	return GrpclbRouteType_GRPCLB_ROUTE_TYPE_UNKNOWN
}

// Client-streaming request.
type StreamingInputCallRequest struct {
	// Optional input payload sent along with the request.
	Payload *Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Whether the server should expect this request to be compressed. This field
	// is "nullable" in order to interoperate seamlessly with servers not able to
	// implement the full compression tests by introspecting the call to verify
	// the request's compression status.
	ExpectCompressed     *BoolValue `protobuf:"bytes,2,opt,name=expect_compressed,json=expectCompressed,proto3" json:"expect_compressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StreamingInputCallRequest) Reset()         { *m = StreamingInputCallRequest{} }
func (m *StreamingInputCallRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingInputCallRequest) ProtoMessage()    {}
func (*StreamingInputCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{5}
}

func (m *StreamingInputCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingInputCallRequest.Unmarshal(m, b)
}
func (m *StreamingInputCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingInputCallRequest.Marshal(b, m, deterministic)
}
func (m *StreamingInputCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingInputCallRequest.Merge(m, src)
}
func (m *StreamingInputCallRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingInputCallRequest.Size(m)
}
func (m *StreamingInputCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingInputCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingInputCallRequest proto.InternalMessageInfo

func (m *StreamingInputCallRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StreamingInputCallRequest) GetExpectCompressed() *BoolValue {
	if m != nil {
		return m.ExpectCompressed
	}
	return nil
}

// Client-streaming response.
type StreamingInputCallResponse struct {
	// Aggregated size of payloads received from the client.
	AggregatedPayloadSize int32    `protobuf:"varint,1,opt,name=aggregated_payload_size,json=aggregatedPayloadSize,proto3" json:"aggregated_payload_size,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *StreamingInputCallResponse) Reset()         { *m = StreamingInputCallResponse{} }
func (m *StreamingInputCallResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingInputCallResponse) ProtoMessage()    {}
func (*StreamingInputCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{6}
}

func (m *StreamingInputCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingInputCallResponse.Unmarshal(m, b)
}
func (m *StreamingInputCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingInputCallResponse.Marshal(b, m, deterministic)
}
func (m *StreamingInputCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingInputCallResponse.Merge(m, src)
}
func (m *StreamingInputCallResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingInputCallResponse.Size(m)
}
func (m *StreamingInputCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingInputCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingInputCallResponse proto.InternalMessageInfo

func (m *StreamingInputCallResponse) GetAggregatedPayloadSize() int32 {
	if m != nil {
		return m.AggregatedPayloadSize
	}
	return 0
}

// Configuration for a particular response.
type ResponseParameters struct {
	// Desired payload sizes in responses from the server.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Desired interval between consecutive responses in the response stream in
	// microseconds.
	IntervalUs int32 `protobuf:"varint,2,opt,name=interval_us,json=intervalUs,proto3" json:"interval_us,omitempty"`
	// Whether to request the server to compress the response. This field is
	// "nullable" in order to interoperate seamlessly with clients not able to
	// implement the full compression tests by introspecting the call to verify
	// the response's compression status.
	Compressed           *BoolValue `protobuf:"bytes,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponseParameters) Reset()         { *m = ResponseParameters{} }
func (m *ResponseParameters) String() string { return proto.CompactTextString(m) }
func (*ResponseParameters) ProtoMessage()    {}
func (*ResponseParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{7}
}

func (m *ResponseParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseParameters.Unmarshal(m, b)
}
func (m *ResponseParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseParameters.Marshal(b, m, deterministic)
}
func (m *ResponseParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseParameters.Merge(m, src)
}
func (m *ResponseParameters) XXX_Size() int {
	return xxx_messageInfo_ResponseParameters.Size(m)
}
func (m *ResponseParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseParameters proto.InternalMessageInfo

func (m *ResponseParameters) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ResponseParameters) GetIntervalUs() int32 {
	if m != nil {
		return m.IntervalUs
	}
	return 0
}

func (m *ResponseParameters) GetCompressed() *BoolValue {
	if m != nil {
		return m.Compressed
	}
	return nil
}

// Server-streaming request.
type StreamingOutputCallRequest struct {
	// Desired payload type in the response from the server.
	// If response_type is RANDOM, the payload from each response in the stream
	// might be of different types. This is to simulate a mixed type of payload
	// stream.
	ResponseType PayloadType `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=grpc.testing.PayloadType" json:"response_type,omitempty"`
	// Configuration for each expected response message.
	ResponseParameters []*ResponseParameters `protobuf:"bytes,2,rep,name=response_parameters,json=responseParameters,proto3" json:"response_parameters,omitempty"`
	// Optional input payload sent along with the request.
	Payload *Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Whether server should return a given status
	ResponseStatus       *EchoStatus `protobuf:"bytes,7,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamingOutputCallRequest) Reset()         { *m = StreamingOutputCallRequest{} }
func (m *StreamingOutputCallRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingOutputCallRequest) ProtoMessage()    {}
func (*StreamingOutputCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{8}
}

func (m *StreamingOutputCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOutputCallRequest.Unmarshal(m, b)
}
func (m *StreamingOutputCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOutputCallRequest.Marshal(b, m, deterministic)
}
func (m *StreamingOutputCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOutputCallRequest.Merge(m, src)
}
func (m *StreamingOutputCallRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingOutputCallRequest.Size(m)
}
func (m *StreamingOutputCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOutputCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOutputCallRequest proto.InternalMessageInfo

func (m *StreamingOutputCallRequest) GetResponseType() PayloadType {
	if m != nil {
		return m.ResponseType
	}
	return PayloadType_COMPRESSABLE
}

func (m *StreamingOutputCallRequest) GetResponseParameters() []*ResponseParameters {
	if m != nil {
		return m.ResponseParameters
	}
	return nil
}

func (m *StreamingOutputCallRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StreamingOutputCallRequest) GetResponseStatus() *EchoStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

// Server-streaming response, as configured by the request and parameters.
type StreamingOutputCallResponse struct {
	// Payload to increase response size.
	Payload              *Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingOutputCallResponse) Reset()         { *m = StreamingOutputCallResponse{} }
func (m *StreamingOutputCallResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingOutputCallResponse) ProtoMessage()    {}
func (*StreamingOutputCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{9}
}

func (m *StreamingOutputCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOutputCallResponse.Unmarshal(m, b)
}
func (m *StreamingOutputCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOutputCallResponse.Marshal(b, m, deterministic)
}
func (m *StreamingOutputCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOutputCallResponse.Merge(m, src)
}
func (m *StreamingOutputCallResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingOutputCallResponse.Size(m)
}
func (m *StreamingOutputCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOutputCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOutputCallResponse proto.InternalMessageInfo

func (m *StreamingOutputCallResponse) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// For reconnect interop test only.
// Client tells server what reconnection parameters it used.
type ReconnectParams struct {
	MaxReconnectBackoffMs int32    `protobuf:"varint,1,opt,name=max_reconnect_backoff_ms,json=maxReconnectBackoffMs,proto3" json:"max_reconnect_backoff_ms,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ReconnectParams) Reset()         { *m = ReconnectParams{} }
func (m *ReconnectParams) String() string { return proto.CompactTextString(m) }
func (*ReconnectParams) ProtoMessage()    {}
func (*ReconnectParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{10}
}

func (m *ReconnectParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReconnectParams.Unmarshal(m, b)
}
func (m *ReconnectParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReconnectParams.Marshal(b, m, deterministic)
}
func (m *ReconnectParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReconnectParams.Merge(m, src)
}
func (m *ReconnectParams) XXX_Size() int {
	return xxx_messageInfo_ReconnectParams.Size(m)
}
func (m *ReconnectParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReconnectParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReconnectParams proto.InternalMessageInfo

func (m *ReconnectParams) GetMaxReconnectBackoffMs() int32 {
	if m != nil {
		return m.MaxReconnectBackoffMs
	}
	return 0
}

// For reconnect interop test only.
// Server tells client whether its reconnects are following the spec and the
// reconnect backoffs it saw.
type ReconnectInfo struct {
	Passed               bool     `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	BackoffMs            []int32  `protobuf:"varint,2,rep,packed,name=backoff_ms,json=backoffMs,proto3" json:"backoff_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReconnectInfo) Reset()         { *m = ReconnectInfo{} }
func (m *ReconnectInfo) String() string { return proto.CompactTextString(m) }
func (*ReconnectInfo) ProtoMessage()    {}
func (*ReconnectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1607a094104f88, []int{11}
}

func (m *ReconnectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReconnectInfo.Unmarshal(m, b)
}
func (m *ReconnectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReconnectInfo.Marshal(b, m, deterministic)
}
func (m *ReconnectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReconnectInfo.Merge(m, src)
}
func (m *ReconnectInfo) XXX_Size() int {
	return xxx_messageInfo_ReconnectInfo.Size(m)
}
func (m *ReconnectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReconnectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReconnectInfo proto.InternalMessageInfo

func (m *ReconnectInfo) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *ReconnectInfo) GetBackoffMs() []int32 {
	if m != nil {
		return m.BackoffMs
	}
	return nil
}

func init() {
	proto.RegisterEnum("grpc.testing.PayloadType", PayloadType_name, PayloadType_value)
	proto.RegisterEnum("grpc.testing.GrpclbRouteType", GrpclbRouteType_name, GrpclbRouteType_value)
	proto.RegisterType((*BoolValue)(nil), "grpc.testing.BoolValue")
	proto.RegisterType((*Payload)(nil), "grpc.testing.Payload")
	proto.RegisterType((*EchoStatus)(nil), "grpc.testing.EchoStatus")
	proto.RegisterType((*SimpleRequest)(nil), "grpc.testing.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "grpc.testing.SimpleResponse")
	proto.RegisterType((*StreamingInputCallRequest)(nil), "grpc.testing.StreamingInputCallRequest")
	proto.RegisterType((*StreamingInputCallResponse)(nil), "grpc.testing.StreamingInputCallResponse")
	proto.RegisterType((*ResponseParameters)(nil), "grpc.testing.ResponseParameters")
	proto.RegisterType((*StreamingOutputCallRequest)(nil), "grpc.testing.StreamingOutputCallRequest")
	proto.RegisterType((*StreamingOutputCallResponse)(nil), "grpc.testing.StreamingOutputCallResponse")
	proto.RegisterType((*ReconnectParams)(nil), "grpc.testing.ReconnectParams")
	proto.RegisterType((*ReconnectInfo)(nil), "grpc.testing.ReconnectInfo")
}

func init() { proto.RegisterFile("grpc/testing/messages.proto", fileDescriptor_7f1607a094104f88) }

var fileDescriptor_7f1607a094104f88 = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0x1c, 0x3b, 0x89, 0x4f, 0x9c, 0xc4, 0x65, 0xd7, 0x56, 0x49, 0x90, 0xd5, 0xd3, 0x76,
	0x61, 0x14, 0xa8, 0x0d, 0xa4, 0xc0, 0x8a, 0xed, 0x62, 0x40, 0xec, 0xba, 0x5d, 0x56, 0xd7, 0xf6,
	0xa8, 0x64, 0xc3, 0x76, 0x23, 0xd0, 0x12, 0xa3, 0x08, 0x93, 0x44, 0x4d, 0xa4, 0x82, 0xb8, 0x97,
	0x7b, 0x84, 0x3d, 0xc2, 0xf6, 0x6e, 0x7b, 0x8e, 0x81, 0xd4, 0xaf, 0x1d, 0xa3, 0x68, 0x9a, 0x3b,
	0xf2, 0xfc, 0xe9, 0xfb, 0xce, 0xc7, 0x43, 0x0a, 0x8e, 0xdc, 0x38, 0xb2, 0xfb, 0x82, 0x72, 0xe1,
	0x85, 0x6e, 0x3f, 0xa0, 0x9c, 0x13, 0x97, 0xf2, 0x5e, 0x14, 0x33, 0xc1, 0x50, 0x4b, 0x3a, 0x7b,
	0x99, 0xd3, 0xf8, 0x0a, 0x9a, 0x03, 0xc6, 0xfc, 0x5f, 0x88, 0x9f, 0x50, 0xf4, 0x05, 0x34, 0xae,
	0xe5, 0x42, 0xd7, 0x3a, 0x5a, 0x77, 0x1b, 0xa7, 0x1b, 0x63, 0x0c, 0x5b, 0x33, 0xb2, 0xf0, 0x19,
	0x71, 0xd0, 0x0b, 0xa8, 0x8b, 0x45, 0x94, 0xfa, 0xf7, 0x4e, 0x0e, 0x7a, 0xd5, 0x52, 0xbd, 0x2c,
	0xe8, 0x7c, 0x11, 0x51, 0xac, 0xc2, 0x10, 0x82, 0xfa, 0x9c, 0x39, 0x0b, 0xbd, 0xd6, 0xd1, 0xba,
	0x2d, 0xac, 0xd6, 0xc6, 0xf7, 0x00, 0x23, 0xfb, 0x8a, 0x99, 0x82, 0x88, 0x84, 0xcb, 0x08, 0x9b,
	0x39, 0x69, 0xc1, 0x06, 0x56, 0x6b, 0xa4, 0xc3, 0x56, 0x06, 0x59, 0x25, 0x36, 0x71, 0xbe, 0x35,
	0xfe, 0xa9, 0xc3, 0xae, 0xe9, 0x05, 0x91, 0x4f, 0x31, 0xfd, 0x33, 0xa1, 0x5c, 0xa0, 0x1f, 0x60,
	0x37, 0xa6, 0x3c, 0x62, 0x21, 0xa7, 0xd6, 0xa7, 0x21, 0x6b, 0xe5, 0xf1, 0x72, 0x87, 0xbe, 0xae,
	0xe4, 0x73, 0xef, 0x43, 0xfa, 0xc5, 0x46, 0x19, 0x64, 0x7a, 0x1f, 0x28, 0xea, 0xc3, 0x56, 0x94,
	0x56, 0xd0, 0x37, 0x3a, 0x5a, 0x77, 0xe7, 0xe4, 0xf1, 0xda, 0xf2, 0x38, 0x8f, 0x92, 0x55, 0x2f,
	0x3d, 0xdf, 0xb7, 0x12, 0x4e, 0xe3, 0x90, 0x04, 0x54, 0xaf, 0xab, 0x7e, 0xb6, 0xa4, 0xf1, 0x22,
	0xb3, 0xa1, 0x2e, 0xb4, 0x55, 0x10, 0x23, 0x89, 0xb8, 0xb2, 0xb8, 0xcd, 0x22, 0xaa, 0x37, 0x54,
	0xdc, 0x9e, 0xb4, 0x4f, 0xa5, 0xd9, 0x94, 0x56, 0xf4, 0x23, 0x3c, 0x2a, 0x40, 0xda, 0x2c, 0x88,
	0x62, 0xca, 0x39, 0x75, 0xf4, 0x4d, 0x85, 0xe5, 0xe9, 0x32, 0x96, 0x42, 0x4c, 0x8c, 0xf2, 0x9c,
	0x61, 0x91, 0x82, 0x4e, 0x61, 0xbf, 0xa4, 0xab, 0x14, 0xd0, 0xb7, 0x54, 0x15, 0x7d, 0xb9, 0x4a,
	0xa9, 0x10, 0xde, 0x2b, 0x5a, 0x91, 0x2a, 0xf6, 0x1a, 0x1e, 0xd2, 0x9b, 0x88, 0xda, 0xa2, 0x0a,
	0x65, 0xfb, 0xe3, 0x50, 0xda, 0x69, 0x46, 0x05, 0xc8, 0x37, 0xa0, 0x48, 0x5a, 0x9c, 0xc6, 0xd7,
	0x34, 0xb6, 0x3c, 0x47, 0x6f, 0x96, 0x2d, 0x32, 0x95, 0xf1, 0xcc, 0x41, 0x2f, 0xe1, 0x89, 0x8a,
	0x92, 0x65, 0xfd, 0xb9, 0x15, 0xb3, 0x44, 0x64, 0x32, 0x83, 0x8a, 0x7e, 0x24, 0xbd, 0x6f, 0x95,
	0x13, 0x4b, 0x9f, 0x94, 0xd4, 0xf8, 0x4f, 0x83, 0xbd, 0xfc, 0x90, 0xa4, 0xc8, 0xab, 0x02, 0x6a,
	0x9f, 0x24, 0xe0, 0x21, 0x6c, 0x17, 0xda, 0xa5, 0x67, 0xb0, 0xd8, 0xa3, 0x67, 0xb0, 0x53, 0x95,
	0x6c, 0x43, 0xb9, 0x81, 0x95, 0x72, 0x1d, 0x41, 0xb3, 0xa4, 0x55, 0x4f, 0xb3, 0x79, 0x4e, 0xe9,
	0x0c, 0x1e, 0xde, 0x66, 0xd3, 0x50, 0x87, 0xf6, 0x78, 0x19, 0xd4, 0x0a, 0x2f, 0xbc, 0xef, 0xae,
	0x10, 0xfd, 0x5b, 0x83, 0x03, 0x53, 0xc4, 0x94, 0x04, 0x5e, 0xe8, 0x9e, 0x85, 0x51, 0x22, 0x86,
	0xc4, 0xf7, 0xf3, 0xc9, 0xb8, 0x33, 0xe7, 0xb5, 0xc2, 0xd6, 0xee, 0x28, 0xac, 0x71, 0x0e, 0x87,
	0xeb, 0x30, 0x65, 0x42, 0x7c, 0x0b, 0x4f, 0x89, 0xeb, 0xc6, 0xd4, 0x25, 0x82, 0x3a, 0x56, 0xf6,
	0xe5, 0x74, 0xf0, 0xd2, 0x1b, 0xe0, 0x71, 0xe9, 0xce, 0x00, 0xca, 0x09, 0x34, 0xfe, 0xd2, 0x00,
	0xe5, 0x45, 0x66, 0x24, 0x26, 0x01, 0x15, 0x34, 0x56, 0xb7, 0x47, 0x25, 0x57, 0xad, 0xa5, 0x3c,
	0x5e, 0x28, 0x68, 0x7c, 0x4d, 0xe4, 0xfc, 0x65, 0xf3, 0x0c, 0xb9, 0xe9, 0x82, 0xa3, 0x57, 0x00,
	0x15, 0x82, 0x1b, 0x1f, 0x27, 0x58, 0x09, 0x35, 0xfe, 0xad, 0x55, 0xb8, 0x4d, 0x13, 0xb1, 0xd2,
	0xf0, 0xfb, 0x5e, 0x45, 0x3f, 0x57, 0xa6, 0x3c, 0x2a, 0x38, 0xea, 0xb5, 0xce, 0x46, 0x77, 0xe7,
	0xa4, 0xb3, 0x5c, 0xe5, 0x76, 0x2f, 0xca, 0x71, 0xaf, 0xf4, 0xe7, 0xce, 0x17, 0xd7, 0xfd, 0xef,
	0x07, 0x63, 0x02, 0x47, 0x6b, 0x9b, 0xf4, 0x99, 0xa3, 0x68, 0xfc, 0x04, 0xfb, 0x98, 0xda, 0x2c,
	0x0c, 0xa9, 0x2d, 0x14, 0x35, 0xa9, 0xa0, 0x1e, 0x90, 0x1b, 0x2b, 0xce, 0xcd, 0xd6, 0x9c, 0xd8,
	0x7f, 0xb0, 0xcb, 0x4b, 0x2b, 0xe0, 0xf9, 0x31, 0x0a, 0xc8, 0x4d, 0x91, 0x35, 0x48, 0xbd, 0xef,
	0xb9, 0xf1, 0x06, 0x76, 0x0b, 0xeb, 0x59, 0x78, 0xc9, 0xd0, 0x13, 0xd8, 0x8c, 0x88, 0x3a, 0x07,
	0xe9, 0x8b, 0x97, 0xed, 0xd0, 0x31, 0x40, 0xa5, 0xa6, 0x94, 0xa0, 0x81, 0x9b, 0xf3, 0xbc, 0xce,
	0xf3, 0x67, 0xb0, 0x53, 0xd1, 0x11, 0xb5, 0xa1, 0x35, 0x9c, 0xbe, 0x9f, 0xe1, 0x91, 0x69, 0x9e,
	0x0e, 0xc6, 0xa3, 0xf6, 0x83, 0xe7, 0x0c, 0xf6, 0x57, 0xc6, 0x17, 0x1d, 0xc3, 0xc1, 0x5b, 0x3c,
	0x1b, 0x8e, 0x07, 0x16, 0x9e, 0x5e, 0x9c, 0x8f, 0xac, 0xf3, 0xdf, 0x66, 0x23, 0xeb, 0x62, 0xf2,
	0x6e, 0x32, 0xfd, 0x75, 0xd2, 0x7e, 0x80, 0xbe, 0x84, 0xc3, 0xdb, 0xee, 0x37, 0xa7, 0xe3, 0xf1,
	0xe0, 0x74, 0xf8, 0xae, 0xad, 0xad, 0x4f, 0x97, 0xbe, 0xd1, 0xe4, 0x75, 0xbb, 0x36, 0xf8, 0xee,
	0xf7, 0x57, 0xae, 0x27, 0xae, 0x92, 0x79, 0xcf, 0x66, 0x41, 0x5f, 0x3e, 0xa3, 0x73, 0x9f, 0x31,
	0x87, 0x3a, 0x7d, 0xd9, 0xdd, 0x17, 0xea, 0xe5, 0xef, 0xbb, 0x34, 0xcc, 0x16, 0x95, 0xdf, 0x83,
	0xf9, 0xa6, 0xb2, 0xbd, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x68, 0x29, 0xfc, 0xc7, 0x35, 0x08,
	0x00, 0x00,
}
