// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/core/stats.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bucket struct {
	Start                float64  `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c46aa61ece466e, []int{0}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetStart() float64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Bucket) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Histogram struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Histogram) Reset()         { *m = Histogram{} }
func (m *Histogram) String() string { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()    {}
func (*Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c46aa61ece466e, []int{1}
}

func (m *Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram.Unmarshal(m, b)
}
func (m *Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram.Marshal(b, m, deterministic)
}
func (m *Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram.Merge(m, src)
}
func (m *Histogram) XXX_Size() int {
	return xxx_messageInfo_Histogram.Size(m)
}
func (m *Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram proto.InternalMessageInfo

func (m *Histogram) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type Metric struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Metric_Count
	//	*Metric_Histogram
	Value                isMetric_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c46aa61ece466e, []int{2}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_Count struct {
	Count uint64 `protobuf:"varint,10,opt,name=count,proto3,oneof"`
}

type Metric_Histogram struct {
	Histogram *Histogram `protobuf:"bytes,11,opt,name=histogram,proto3,oneof"`
}

func (*Metric_Count) isMetric_Value() {}

func (*Metric_Histogram) isMetric_Value() {}

func (m *Metric) GetValue() isMetric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetCount() uint64 {
	if x, ok := m.GetValue().(*Metric_Count); ok {
		return x.Count
	}
	return 0
}

func (m *Metric) GetHistogram() *Histogram {
	if x, ok := m.GetValue().(*Metric_Histogram); ok {
		return x.Histogram
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metric_Count)(nil),
		(*Metric_Histogram)(nil),
	}
}

type Stats struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c46aa61ece466e, []int{3}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*Bucket)(nil), "grpc.core.Bucket")
	proto.RegisterType((*Histogram)(nil), "grpc.core.Histogram")
	proto.RegisterType((*Metric)(nil), "grpc.core.Metric")
	proto.RegisterType((*Stats)(nil), "grpc.core.Stats")
}

func init() { proto.RegisterFile("grpc/core/stats.proto", fileDescriptor_e6c46aa61ece466e) }

var fileDescriptor_e6c46aa61ece466e = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x6f, 0x83, 0x30,
	0x10, 0x85, 0xe3, 0x36, 0x10, 0x71, 0x4c, 0xb5, 0xd2, 0x8a, 0x11, 0x31, 0x21, 0x55, 0xc5, 0x52,
	0x8a, 0xaa, 0xce, 0x4c, 0x2c, 0x5d, 0xdc, 0xad, 0x9b, 0x31, 0x16, 0x41, 0x0d, 0x38, 0xb2, 0x8f,
	0xfe, 0xfe, 0xca, 0x26, 0x4e, 0x3b, 0x64, 0xf3, 0x3d, 0x3d, 0xbf, 0xef, 0xdd, 0xc1, 0xe3, 0x60,
	0xce, 0x92, 0x49, 0x6d, 0x14, 0xb3, 0x28, 0xd0, 0x56, 0x67, 0xa3, 0x51, 0xd3, 0xc4, 0xc9, 0x95,
	0x93, 0x8b, 0x1a, 0xe2, 0x66, 0x91, 0xdf, 0x0a, 0xe9, 0x1e, 0x22, 0x8b, 0xc2, 0x60, 0x46, 0x72,
	0x52, 0x12, 0xbe, 0x0e, 0x4e, 0x95, 0x7a, 0x99, 0x31, 0xbb, 0xcb, 0x49, 0xb9, 0xe5, 0xeb, 0x50,
	0xbc, 0x43, 0xd2, 0x8e, 0x16, 0xf5, 0x60, 0xc4, 0x44, 0x9f, 0x61, 0xd7, 0xf9, 0x08, 0x9b, 0x91,
	0xfc, 0xbe, 0x4c, 0x0f, 0x0f, 0xd5, 0x35, 0xbf, 0x5a, 0xc3, 0x79, 0x70, 0x14, 0x16, 0xe2, 0x0f,
	0x85, 0x66, 0x94, 0x94, 0xc2, 0x76, 0x16, 0x93, 0xf2, 0xb8, 0x84, 0xfb, 0x37, 0x7d, 0x0a, 0x34,
	0x70, 0xb4, 0x76, 0x73, 0xe1, 0xd1, 0x1a, 0x92, 0x63, 0xe0, 0x65, 0x69, 0x4e, 0xca, 0xf4, 0xb0,
	0xff, 0x07, 0xb9, 0x76, 0x69, 0x37, 0xfc, 0xcf, 0xd8, 0xec, 0x20, 0xfa, 0x11, 0xa7, 0xc5, 0x2d,
	0x19, 0x7d, 0xba, 0xf5, 0x5d, 0xd5, 0xc9, 0xd3, 0x6f, 0x55, 0x5d, 0x7b, 0xf1, 0xe0, 0x68, 0xde,
	0xbe, 0xea, 0x61, 0xc4, 0xe3, 0xd2, 0x55, 0x52, 0x4f, 0x4c, 0xea, 0x5e, 0x75, 0x27, 0xad, 0x7b,
	0xd5, 0x33, 0xf7, 0xe7, 0xc5, 0x9f, 0x92, 0x0d, 0x6a, 0xbe, 0x3c, 0xc2, 0xa5, 0xbb, 0xd8, 0x0b,
	0xaf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x82, 0xb9, 0x71, 0x7d, 0x01, 0x00, 0x00,
}
